using System.Collections.Generic;

namespace Voba.Models
{
    // Data model representing a single meal idea generated by the Gemma AI during the brainstorming phase.
    public class RecipeOption
    {
        public string Name { get; set; } = string.Empty;
        public List<string> Ingredients { get; set; } = new();
        public decimal EstimatedCost { get; set; }
    }
}