namespace Voba.AI.Interpreter
{
    /// <summary>
    /// TERMINAL EXPRESSION — No restrictions (Interpreter pattern).
    /// Used when the user left the dietary field blank.
    /// </summary>
    public class NoneExpression : IRestrictionExpression
    {
        public string Interpret() => "No dietary restrictions or allergies.";
    }

    /// <summary>
    /// TERMINAL EXPRESSION — Unrecognised input (Interpreter pattern).
    /// Fallback for any restriction the parser could not classify as a
    /// known diet or allergen. Passes the raw text to Gemma with a
    /// generic compliance instruction.
    /// </summary>
    public class UnknownRestrictionExpression : IRestrictionExpression
    {
        // Holds the exact text generated by the Gemma AI when the rule does not match known diet or allergy lists.
        private readonly string _raw;

        // Called when the parser cannot figure out exactly what category the AI output belongs to.
        public UnknownRestrictionExpression(string raw) => _raw = raw;

        // Formats a generic safety warning for the MAUI front-end to display on the recipe screen.
        // Makes sure the user still sees the restriction even if the app does not have a detailed rule for it.
        public string Interpret() =>
            $"RESTRICTION: {_raw} — strictly avoid any ingredient that conflicts with this.";
    }
}