using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Voba.Models;
using Voba.Spoonacular;

namespace Voba.AI.Pipeline.Handlers
{
    /// <summary>
    /// Pipeline handler responsible for updating recipe cost estimates using the Spoonacular API.
    /// Executes after initial recipe ideation and before full recipe generation.
    /// Utilizes batch processing to minimize API quota consumption.
    /// </summary>
    public class SpoonacularPricingHandler : RecipePipelineHandler
    {
        private readonly SpoonacularService _spoonacular;

        /// <summary>
        /// Initializes the handler with the required Spoonacular service dependency.
        /// </summary>
        public SpoonacularPricingHandler(SpoonacularService spoonacular)
        {
            _spoonacular = spoonacular;
        }

        /// <summary>
        /// Intercepts the pipeline execution to process pricing for proposed recipe options.
        /// </summary>
        /// <param name="context">The current recipe generation context.</param>
        public override async Task HandleAsync(RecipeGenerationContext context)
        {
            // Terminate local execution if no recipes were generated by the previous handler.
            if (context.ProposedOptions.Count == 0)
            {
                await base.HandleAsync(context);
                return;
            }

            // Iterate through each proposed recipe to update pricing estimates.
            foreach (var recipe in context.ProposedOptions)
            {
                await RepriceSingleRecipeAsync(recipe);
            }

            // Pass execution to the next handler in the pipeline.
            await base.HandleAsync(context);
        }

        // ── Private ──────────────────────────────────────────────────────────

        /// <summary>
        /// Executes a batch pricing request for a single recipe's ingredient list and updates the estimated cost.
        /// </summary>
        private async Task RepriceSingleRecipeAsync(RecipeOption recipe)
        {
            // Execute batch API call to retrieve prices for all ingredients simultaneously.
            Dictionary<string, decimal> prices =
                await _spoonacular.GetBatchPricesAsync(recipe.Ingredients);

            // Fallback: Retain the original AI-generated estimate if the API call fails or returns empty.
            if (prices.Count == 0)
                return;

            decimal runningTotal = 0m;
            int pricedCount = 0;

            // Aggregate the resolved USD prices for matched ingredients.
            foreach (string rawIngredient in recipe.Ingredients)
            {
                if (prices.TryGetValue(rawIngredient, out decimal usd))
                {
                    runningTotal += usd;
                    pricedCount++;
                }
            }

            // Compute the final estimated cost if at least one ingredient was successfully priced.
            if (pricedCount > 0)
            {
                // Calculate a scaling factor to account for unpriced ingredients.
                decimal scalingFactor = (decimal)recipe.Ingredients.Count / pricedCount;

                // Apply the scaling factor to the running total and round to two decimal places.
                recipe.EstimatedCost = Math.Round(runningTotal * scalingFactor, 2);
            }
        }
    }
}